"""contest session table

Revision ID: 0f7efb922f4d
Revises: 
Create Date: 2026-01-19 19:24:10.535533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7efb922f4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_session',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('duration_in_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.BigInteger(), nullable=False),
    sa.Column('p1_cf_contest_id', sa.String(length=255), nullable=False),
    sa.Column('p1_cf_index', sa.String(length=255), nullable=False),
    sa.Column('p2_cf_contest_id', sa.String(length=255), nullable=False),
    sa.Column('p2_cf_index', sa.String(length=255), nullable=False),
    sa.Column('p3_cf_contest_id', sa.String(length=255), nullable=False),
    sa.Column('p3_cf_index', sa.String(length=255), nullable=False),
    sa.Column('p4_cf_contest_id', sa.String(length=255), nullable=False),
    sa.Column('p4_cf_index', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contest_session_problems_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('problem_number', sa.Integer(), nullable=False),
    sa.Column('problem_contest_id', sa.String(length=255), nullable=False),
    sa.Column('problem_index', sa.String(length=255), nullable=False),
    sa.Column('problem_rating', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('accepted_at', sa.String(length=255), nullable=True),
    sa.Column('solved_in_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['contest_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contest_session_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=False),
    sa.Column('performance', sa.Integer(), nullable=False),
    sa.Column('rating_before', sa.Integer(), nullable=False),
    sa.Column('rating_after', sa.Integer(), nullable=False),
    sa.Column('rating_delta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['contest_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contest_session_seen_problem',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('cf_problem_contest_id', sa.String(length=255), nullable=False),
    sa.Column('cf_problem_index', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['contest_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'cf_problem_contest_id', 'cf_problem_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contest_session_seen_problem')
    op.drop_table('contest_session_result')
    op.drop_table('contest_session_problems_status')
    op.drop_table('contest_session')
    # ### end Alembic commands ###
