"""user_and_contest_level

Revision ID: 1b6a62e5f295
Revises: 38c23f5f5fcf
Create Date: 2026-01-25 19:34:45.898878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6a62e5f295'
down_revision: Union[str, Sequence[str], None] = '38c23f5f5fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('duration_in_min', sa.Integer(), nullable=False),
    sa.Column('performance', sa.Integer(), nullable=False),
    sa.Column('p1_rating', sa.Integer(), nullable=False),
    sa.Column('p2_rating', sa.Integer(), nullable=False),
    sa.Column('p3_rating', sa.Integer(), nullable=False),
    sa.Column('p4_rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('codeforces_handle', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('contest_levels')
    # ### end Alembic commands ###
