"""contest_theme

Revision ID: 1ff5fb2df58b
Revises: e2f6a95b3d4e
Create Date: 2026-02-22 11:30:19.141658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff5fb2df58b'
down_revision: Union[str, Sequence[str], None] = 'e2f6a95b3d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_theme',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme')
    )
    op.drop_index(op.f('ix_contest_session_status'), table_name='contest_session')
    op.drop_index(op.f('ix_contest_session_user_id'), table_name='contest_session')
    op.drop_index(op.f('ix_contest_session_user_id_status'), table_name='contest_session')
    op.drop_index(op.f('ix_contest_session_problems_status_session_id'), table_name='contest_session_problems_status')
    op.create_unique_constraint(None, 'users', ['codeforces_handle'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_contest_session_problems_status_session_id'), 'contest_session_problems_status', ['session_id'], unique=False)
    op.create_index(op.f('ix_contest_session_user_id_status'), 'contest_session', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_contest_session_user_id'), 'contest_session', ['user_id'], unique=False)
    op.create_index(op.f('ix_contest_session_status'), 'contest_session', ['status'], unique=False)
    op.drop_table('contest_theme')
    # ### end Alembic commands ###
