"""updated ddl contest session

Revision ID: a81e39f8ee47
Revises: 0f7efb922f4d
Create Date: 2026-01-19 22:19:34.191330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81e39f8ee47'
down_revision: Union[str, Sequence[str], None] = '0f7efb922f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_session', sa.Column('p1_cf_contestID', sa.String(length=255), nullable=False))
    op.add_column('contest_session', sa.Column('p2_cf_contestID', sa.String(length=255), nullable=False))
    op.add_column('contest_session', sa.Column('p3_cf_contestID', sa.String(length=255), nullable=False))
    op.add_column('contest_session', sa.Column('p4_cf_contestID', sa.String(length=255), nullable=False))
    op.alter_column('contest_session', 'starts_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('contest_session', 'p1_cf_contest_id')
    op.drop_column('contest_session', 'p3_cf_contest_id')
    op.drop_column('contest_session', 'p2_cf_contest_id')
    op.drop_column('contest_session', 'p4_cf_contest_id')
    op.add_column('contest_session_problems_status', sa.Column('problem_contestID', sa.String(length=255), nullable=False))
    op.drop_column('contest_session_problems_status', 'problem_contest_id')
    op.add_column('contest_session_seen_problem', sa.Column('cf_problem_contestID', sa.String(length=255), nullable=False))
    op.drop_column('contest_session_seen_problem', 'cf_problem_contest_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_session_seen_problem', sa.Column('cf_problem_contest_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('contest_session_seen_problem', 'cf_problem_contestID')
    op.add_column('contest_session_problems_status', sa.Column('problem_contest_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('contest_session_problems_status', 'problem_contestID')
    op.add_column('contest_session', sa.Column('p4_cf_contest_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('contest_session', sa.Column('p2_cf_contest_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('contest_session', sa.Column('p3_cf_contest_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('contest_session', sa.Column('p1_cf_contest_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('contest_session', 'starts_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('contest_session', 'p4_cf_contestID')
    op.drop_column('contest_session', 'p3_cf_contestID')
    op.drop_column('contest_session', 'p2_cf_contestID')
    op.drop_column('contest_session', 'p1_cf_contestID')
    # ### end Alembic commands ###
