"""add performance in ContestLevel

Revision ID: 160f825a5df5
Revises: 637771ec32bd
Create Date: 2025-10-23 18:06:19.712450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160f825a5df5'
down_revision: Union[str, Sequence[str], None] = '637771ec32bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_level', sa.Column('performance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest_level', 'performance')
    # ### end Alembic commands ###
