"""contest_session_and_level_sheet_v2

Revision ID: 637771ec32bd
Revises: 780b73967c5a
Create Date: 2025-10-23 18:00:45.743534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '637771ec32bd'
down_revision: Union[str, Sequence[str], None] = '780b73967c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_level',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('rating_1', sa.Integer(), nullable=False),
    sa.Column('rating_2', sa.Integer(), nullable=False),
    sa.Column('rating_3', sa.Integer(), nullable=False),
    sa.Column('rating_4', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('level')
    )
    op.create_table('contest_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contest_level', sa.Integer(), nullable=False),
    sa.Column('contest_theme', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('rating_1', sa.Integer(), nullable=False),
    sa.Column('rating_2', sa.Integer(), nullable=False),
    sa.Column('rating_3', sa.Integer(), nullable=False),
    sa.Column('rating_4', sa.Integer(), nullable=False),
    sa.Column('t1', sa.String(), nullable=True),
    sa.Column('t2', sa.String(), nullable=True),
    sa.Column('t3', sa.String(), nullable=True),
    sa.Column('t4', sa.String(), nullable=True),
    sa.Column('problem_1_id', sa.String(), nullable=False),
    sa.Column('problem_2_id', sa.String(), nullable=False),
    sa.Column('problem_3_id', sa.String(), nullable=False),
    sa.Column('problem_4_id', sa.String(), nullable=False),
    sa.Column('problem_1_index', sa.String(), nullable=False),
    sa.Column('problem_2_index', sa.String(), nullable=False),
    sa.Column('problem_3_index', sa.String(), nullable=False),
    sa.Column('problem_4_index', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('problem_listed', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contest_session')
    op.drop_table('contest_level')
    # ### end Alembic commands ###
