class ErrorConstants:
    USER_ALREADY_EXISTS = "User already exists"
    DATABASE_ERROR = "Failed read/write to database"
    USER_ALREADY_EXISTS = "User with this username already exists"
    INVALID_CREDENTIALS = "Invalid username or password"
    INVALID_TOKEN = "Invalid token"
    USER_NOT_FOUND = "User not found"
    UNSOLVED_PROBLEM_NOT_FOUND = "Unsolved problem not found from codeforces"
    CONTEST_LEVEL_NOT_FOUND = "Contest level not found"
    CODEFORCES_API_ERROR = "Failed to get problem from codeforces"
    CONTEST_SESSION_NOT_FOUND = "Contest session not found"
    CONTEST_SESSION_DOES_NOT_BELONG_TO_USER = "Contest session does not belong to user"